config:
- equipName: clean
  fileName: clean08-37
  taktTime: 2000
  offsetDelay: 300
  consumerTopic: clean
  producerTopic: factory
- equipName: cvd
  fileName: cvd03-37
  taktTime: 2000
  offsetDelay: 300
  consumerTopic: cvd
  producerTopic: factory
- equipName: hack
  fileName: hack03-37
  taktTime: 2000
  offsetDelay: 700
  consumerTopic: hack
  producerTopic: factory
- equipName: print
  fileName: print02-34
  taktTime: 2000
  offsetDelay: 900
  consumerTopic: print
  producerTopic: factory
- equipName: scan
  fileName: scan01-34
  taktTime: 2000
  offsetDelay: 1300
  consumerTopic: scan
  producerTopic: factory
